linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - goimports
    - gocritic
    - bodyclose
    - depguard
    - errcheck
    - gochecknoglobals
    - gocognit
    - gosec
    - lll
    - nakedret
    - noctx
    - nolintlint

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentFormatting
      - hugeParam
  gosec:
    severity: "medium"
  lll:
    line-length: 120
  goanalysis:
    disabled: true
  govet:
    checks: ["fieldalignment"]
  depguard:
    rules:
      main:
        # List of allowed packages
        allow:
          - $gostd # Allows all Go standard library packages
          - github.com/charmbracelet/bubbletea
          - github.com/mattn/go-sqlite3
          - go.uber.org/zap
          - github.com/google/wire
          - github.com/spf13/cobra
          - github.com/spf13/viper
          # GUI package
          - fyne.io/fyne/v2
        # Packages that are not allowed
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use go.uber.org/zap for logging instead"
          - pkg: "log"
            desc: "use go.uber.org/zap for logging instead"
          - pkg: "github.com/jinzhu/gorm"
            desc: "use raw SQL with database/sql instead"
          - pkg: "fmt"
            desc: "use go.uber.org/zap for logging instead"
          # Deny other GUI toolkits to ensure consistency
          - pkg: "github.com/gotk3/gotk3"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/lxn/win"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/progrium/macdriver"
            desc: "use fyne.io/fyne/v2 for GUI instead"
        ignore-files:
          - ".*_test.go$"
          - "examples/*"
          - "internal/testing/*"

output:
  formats:
    - format: colored-line-number
  sort-results: true
