linters:
  disable-all: true
  enable:
  - gocritic
  - gofmt
  - gosimple
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - typecheck
  - unparam
  - unused
  - mnd
  - copyloopvar

linters-settings:
  gocritic:
    enabled-tags:
    - diagnostic
    - style
    - performance
    disabled-checks:
    - hugeParam
    - importShadow

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - build/
  - coverage/

output:
  sort-results: true
  formats:
  - format: colored-line-number

run:
  timeout: 5m
