# .golangci.yml
linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - goimports
    - gocritic

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - hugeParam
  goanalysis:
    disabled: true

output:
  formats:
    - format: colored-line-number
  sort-results: true
  