# .golangci.yml
linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - goimports
    - gocritic

run:
  timeout: 5m

issues:
  exclude-files:
    - ".*_linux\\.go$"
    - ".*_windows\\.go$"
    - ".*_darwin\\.go$"
  exclude-dirs:
    - vendor
  exclude-rules:
    - linters: [typecheck]
      path: cmd/godo/main\.go
    - linters: [typecheck]
      path: internal/systray/systray\.go
    - linters: [typecheck]
      path: internal/hotkey/
    - linters: [typecheck]
      path: internal/ui/

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - hugeParam
  goanalysis:
    disabled: true

output:
  formats:
    - format: colored-line-number
  sort-results: true
  