linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - bodyclose
    - depguard
    - errcheck
    - gochecknoglobals
    - gocognit
    - gosec
    - lll
    - nakedret
    - noctx
    - nolintlint
    - revive

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentFormatting
      - hugeParam
  gosec:
    severity: "medium"
  lll:
    line-length: 120
  govet:
    checks: ["fieldalignment"]
  goimports:
    local-prefixes: github.com/jonesrussell/godo
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/mattn/go-sqlite3
          - go.uber.org/zap
          - github.com/google/wire
          - fyne.io/fyne/v2
          - gopkg.in/yaml.v3
          - github.com/stretchr/testify
          - github.com/marcsauter/single
          - golang.design/x/hotkey
          - github.com/google/uuid
          - github.com/spf13/viper
          - github.com/jonesrussell/godo/internal
          - github.com/jonesrussell/godo/pkg
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use go.uber.org/zap for logging instead"
          - pkg: "log"
            desc: "use go.uber.org/zap for logging instead"
          - pkg: "github.com/jinzhu/gorm"
            desc: "use raw SQL with database/sql instead"
          - pkg: "github.com/gotk3/gotk3"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/lxn/win"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/progrium/macdriver"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/charmbracelet/bubbletea"
            desc: "use fyne.io/fyne/v2 for GUI instead"
          - pkg: "github.com/charmbracelet/bubbles"
            desc: "use fyne.io/fyne/v2 for GUI instead"
      logger:
        files: ["internal/logger/.*\\.go$"]
        path: "github.com/jonesrussell/godo/internal/logger"
        allow:
          - $gostd
          - go.uber.org/zap
          - github.com/jonesrussell/godo/internal/common
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use go.uber.org/zap for logging instead"
        ignore-files:
          - ".*_test.go$"
          - "examples/*"
          - "internal/testing/*"
      config:
        files: ["^internal/config/.*\\.go$"]
        path: "github.com/jonesrussell/godo/internal/config"
        allow:
          - $gostd
          - github.com/spf13/viper
          - github.com/jonesrussell/godo/internal/logger
          - github.com/jonesrussell/godo/internal/common
        deny:
          - pkg: "log"
            desc: "use github.com/jonesrussell/godo/internal/logger instead"

output:
  formats:
    - format: colored-line-number
  sort-results: true
