linters:
  enable:
  - gofmt
  - govet
  - errcheck
  - staticcheck
  - gosimple
  - gocritic
  - revive
  - depguard
  - unused
  - gosec

run:
  timeout: 5m

issues:
  exclude:
  - "vendor/"
  exclude-rules:
  - path: _test\.go
    linters:
    - gosec
    - errcheck
  - path: testing\.go
    linters:
    - gosec
    - errcheck

linters-settings:
  revive:
    rules:
    - name: unused-parameter
      severity: warning
      disabled: false
  gocritic:
    enabled-tags:
    - diagnostic
    - style
    - performance
    - experimental
    disabled-checks:
    - commentFormatting
    - hugeParam
  gosec:
    severity: "medium"
  lll:
    line-length: 120
  govet:
    enable-all: true
    disable:
    - shadow
    - fieldalignment
  depguard:
    rules:
      main:
        files:
        - $all
        - "!**/*_test.go"
        - "!**/*testing.go"
        allow:
        - $gostd
        - fyne.io/fyne/v2
        - github.com/go-chi/chi/v5
        - github.com/go-chi/render
        - github.com/google/wire
        - github.com/jonesrussell/godo
        - go.uber.org/zap
        - modernc.org/sqlite
        - golang.design/x/hotkey
        - github.com/spf13/viper
        - github.com/google/uuid
      test:
        files:
        - "**/*_test.go"
        - "**/*testing.go"
        allow:
        - $gostd
        - fyne.io/fyne/v2
        - github.com/stretchr/testify
        - github.com/google/wire
        - github.com/jonesrussell/godo
        - go.uber.org/zap
        - github.com/google/uuid
        - modernc.org/sqlite
        - golang.design/x/hotkey
