linters:
  disable-all: true
  enable:
  - gocritic
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - typecheck
  - unparam
  - unused
  - mnd
  - copyloopvar # replacement for exportloopref

linters-settings:
  depguard:
    rules:
      dashboard-ui:
        files:
        - internal/ui/**/*.go
        deny:
        - pkg: fmt
          desc: "use logger package for output in dashboard UI"
  gocritic:
    enabled-tags:
    - diagnostic
    - style
    - performance
    disabled-checks:
    - hugeParam # Disable hugeParam check as it's not relevant for our UI components
  mnd:
    ignored-numbers:
    - '0o755' # Common file permission
    - '4' # Common UI padding/margin
    - '6' # Common UI padding/margin
    ignored-files:
    - 'internal/ui/*'
    - 'internal/logger/provider.go'

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
  - build/
  - coverage/

output:
  formats:
  - format: colored-line-number
