# .golangci.yml
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - revive
    - unused
    - goimports
    - gocritic

run:
  go: '1.23'
  build-tags:
    - windows
    - linux
    - darwin
  allow-parallel-runners: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - hugeParam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
    - path: internal/hotkey/
      text: "unused-parameter"
      linters:
        - revive
    - path: internal/hotkey/types_(windows|darwin|linux)\.go
      text: "DefaultConfig redeclared"
      linters:
        - typecheck
    - path: internal/hotkey/hotkey_(windows|darwin|linux)\.go
      text: "newPlatformHotkeyManager redeclared"
      linters:
        - typecheck
    - path: internal/ui/quicknote_(windows|darwin|linux)\.go
      text: "newPlatformQuickNoteUI redeclared"
      linters:
        - typecheck
    - path: internal/hotkey/hotkey_(darwin|linux)\.go
      text: "does not implement HotkeyManager \\(missing method Stop\\)"
      linters:
        - typecheck
    - path: internal/config/config\.go
      text: "undefined: yaml"
      linters:
        - typecheck
  