# .golangci.yml
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - revive
    - unused

run:
  go: '1.23'

output:
  formats:
    - format: colored-line-number

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  