version: 1

before:
  hooks:
  - go mod tidy

builds:
- id: windows
  main: ./main.go
  env:
  - CGO_ENABLED=1
  - CC=x86_64-w64-mingw32-gcc
  goos:
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  tags:
  - windows
  hooks:
    pre:
    - cmd: go install github.com/google/wire/cmd/wire@latest
    - cmd: sh -c "cd internal/application/container && wire gen -tags windows"

- id: linux
  main: ./main.go
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  tags:
  - linux
  hooks:
    pre:
    - cmd: go install github.com/google/wire/cmd/wire@latest
    - cmd: sh -c "cd internal/application/container && wire gen -tags linux"

archives:
- id: windows
  builds: [ windows ]
  name_template: "{{ .ProjectName }}_{{ .Version }}_Windows_{{ .Arch }}"
  format: zip
  files:
  - LICENSE
  - README.md
  - configs/*.yaml

- id: linux
  builds: [ linux ]
  name_template: "{{ .ProjectName }}_{{ .Version }}_Linux_{{ .Arch }}"
  format: tar.gz
  files:
  - LICENSE
  - README.md
  - configs/*.yaml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - Merge pull request
    - Merge branch

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Godo {{ .Tag }} ({{ .Date }})

    Welcome to this new release!
  footer: |
    **Full Changelog**: https://github.com/jonesrussell/godo/compare/{{ .PreviousTag }}...{{ .Tag }}

  discussion_category_name: Releases
