Website = "https://github.com/jonesrussell/godo"

[Details]
  Icon = "icon.png"
  Name = "Godo"
  ID = "com.jonesrussell.godo"
  Version = "0.1.0"
  Build = 9

[Source]
  Repo = "https://github.com/jonesrussell/godo"
  Dir = "."

[Development]
  HelperText = "Development build with debug symbols"

[Release]
  HelperText = "Release build without debug symbols"

[LinuxAndBSD]
  GenericName = "Note Application"
  Categories = ["Utility", "Office"]
  Comment = "Quick-note and note management application"
  Keywords = ["notes", "productivity", "quick-note"]
