version: '3'

vars:
  GO_VERSION: 1.23
  CURRENT_OS:
    sh: go env GOOS

tasks:
  default:
    cmds:
      - task: run

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linters
    deps: [fmt]
    cmds:
      - golangci-lint run ./...

  clean:wire:
    desc: Clean up wire-generated files
    cmds:
      - |
        cd internal/container && \
        {{if eq OS "windows"}}
        cmd /c "del /f *_wire_gen.go 2>nul || exit 0"
        {{else}}
        rm -f *_wire_gen.go || true
        {{end}}

  clean:docker:
    desc: Clean up Docker containers
    cmds:
      - docker rm -f godo-linux-build 2>nul || true

  wire:windows:
    desc: Generate wire code for Windows
    deps: [clean:wire]
    cmds:
      - cd internal/container && wire gen -tags windows

  wire:linux:
    desc: Generate wire code for Linux
    deps: [clean:wire]
    cmds:
      - cd internal/container && wire gen -tags linux

  build:windows:
    desc: Build for Windows
    deps: [wire:windows]
    cmds:
      - go build -tags "windows nomobile" -o bin/godo.exe cmd/godo/main.go

  build:linux:docker:
    desc: Build Linux binary using Docker
    deps: [wire:linux, clean:docker]
    cmds:
      - docker build -f build/Dockerfile.linux -t godo-linux-builder .
      - docker run --name godo-linux-build godo-linux-builder
      - docker cp godo-linux-build:/app/bin/godo-linux ./bin/
      - docker rm godo-linux-build

  build:all:
    desc: Build for all platforms
    cmds:
      - task: build:windows
      - task: build:linux:docker

  run:
    deps: [wire:windows]
    cmds:
      - go run cmd/godo/main.go

  act:
    desc: Run GitHub Actions locally using act
    cmds:
      - act -s GITHUB_TOKEN="$(gh auth token)" -v -j build -P ubuntu-latest=catthehacker/ubuntu:act-latest

  act:release:
    desc: Run GitHub Actions release workflow locally
    cmds:
      - act -v -j release

  test:windows:
    desc: Run tests on Windows
    deps: [wire:windows]
    cmds:
      - go test -v ./...

  test:linux:
    desc: Run tests on Linux
    deps: [clean:docker]
    cmds:
      - docker build --target test -f build/Dockerfile.linux -t godo-linux-test .
      - docker run --name godo-linux-test godo-linux-test
      - docker rm godo-linux-test

  test:docker:
    deps: [clean:docker]
    cmds:
      - docker build --target test -f build/Dockerfile.linux -t godo-linux-test .

  test:
    desc: Run tests for current platform
    cmds:
      - task: test:{{.CURRENT_OS}}

  lint:
    desc: Run linters for current platform
    cmds:
      - task: lint:{{if eq .CURRENT_OS "windows"}}windows{{else}}docker{{end}}

  lint:windows:
    desc: Run linters on Windows
    deps: [fmt]
    cmds:
      - golangci-lint run ./...

  lint:docker:
      deps: [clean:docker]
      cmds:
        - docker build --target lint -f build/Dockerfile.linux -t godo-linux-lint .

  build:docker:
    deps: [clean:docker]
    cmds:
      - docker build -f build/Dockerfile.linux -t godo-linux .

  wire:docker:
    deps: [clean:docker]
    cmds:
      - docker build --target wire -f build/Dockerfile.linux -t godo-linux-wire .

  clean:docker:
    cmds:
      - docker rm -f godo-linux-build godo-linux-test 2>nul || true
      - docker rmi -f godo-linux-lint godo-linux-test godo-linux-wire godo-linux 2>nul || true
