version: '3'

vars:
  GO_VERSION: 1.23
  CURRENT_OS:
    sh: go env GOOS

tasks:
  clean:wire:
    desc: Clean up wire-generated files
    cmds:
      - |
        cd internal/container && \
        {{if eq OS "windows"}}
        cmd /c "del /f *_wire_gen.go 2>nul || exit 0"
        {{else}}
        rm -f *_wire_gen.go || true
        {{end}}

  clean:docker:
    desc: Clean up Docker containers
    cmds:
      - docker rm -f godo-linux-build 2>nul || true

  wire:windows:
    desc: Generate wire code for Windows
    deps: [clean:wire]
    cmds:
      - cd internal/container && wire gen -tags windows

  wire:linux:
    desc: Generate wire code for Linux
    deps: [clean:wire]
    cmds:
      - cd internal/container && wire gen -tags linux

  build:windows:
    desc: Build for Windows
    deps: [wire:windows]
    cmds:
      - go build -tags "windows nomobile" -o bin/godo.exe cmd/godo/main.go

  build:linux:docker:
    desc: Build Linux binary using Docker
    deps: [wire:linux, clean:docker]
    cmds:
      - docker build -f build/Dockerfile.linux -t godo-linux-builder .
      - docker run --name godo-linux-build godo-linux-builder
      - docker cp godo-linux-build:/app/bin/godo-linux ./bin/
      - docker rm godo-linux-build

  build:all:
    desc: Build for all platforms
    cmds:
      - task: build:windows
      - task: build:linux:docker

  run:
    deps: [wire:windows]
    cmds:
      - go run cmd/godo/main.go
