version: '3'

tasks:
  default:
    cmds:
      - task: run

  wire:
    cmds:
      - cd internal/di && wire

  run:
    deps: [wire]
    cmds:
      - go run cmd/godo/main.go

  debug:
    deps: [wire]
    env:
      DEBUG: "1"
    cmds:
      - go run cmd/godo/main.go

  test:
    desc: Run tests
    deps: [wire]
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/

  dev:
    desc: Run development tasks (fmt, lint, test, build)
    cmds:
      - task: fmt
      - task: wire
      - task: lint
      - task: test
      - task: build

  install:
    desc: Install project dependencies
    cmds:
      - go install github.com/google/wire/cmd/wire@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go mod tidy
      - go mod download

  logs:
    desc: Watch application logs
    platforms: [windows]
    cmds:
      - cmd /C "type logs\godo.log"

  test-coverage:
    desc: Run tests with coverage report
    deps: [wire]
    cmds:
      - go test -race -coverprofile=coverage.out -coverpkg=./... ./...
      - go tool cover -html=coverage.out -o coverage.html
      - go tool cover -func=coverage.out

  test-coverage-threshold:
    desc: Run tests and check coverage threshold
    deps: [wire]
    cmds:
      - cmd: bash scripts/test-coverage.sh
        platforms: [windows]
      - cmd: ./scripts/test-coverage.sh
        platforms: [linux, darwin]