version: '3'

vars:
  GO_VERSION: 1.23
  GOOS:
    sh: go env GOOS

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Run the application
    deps: [wire]
    cmds:
      - go run cmd/godo/main.go

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  clean:
    desc: Clean up generated files and Docker artifacts
    cmds:
      - rm -rf bin/* internal/container/*_wire_gen.go
      - docker rm -f godo-linux-test godo-linux-build godo-linux-lint || true
      - docker rmi -f godo-linux-test godo-linux-builder godo-linux-wire godo-linux-lint || true

  wire:windows:
    desc: Generate wire code for Windows
    cmds:
      - cd internal/container; wire gen -tags windows

  wire:linux:
    desc: Generate wire code for Linux
    cmds:
      - cd internal/container; wire gen -tags linux

  wire:
    desc: Generate wire code for current platform
    cmds:
      - task: wire:{{if eq OS "windows"}}windows{{else}}linux{{end}}

  build:
    desc: Build for current platform
    cmds:
      - task: build:{{if eq OS "windows"}}windows{{else}}linux{{end}}

  build:windows:
    desc: Build for Windows
    deps: [wire:windows]
    cmds:
      - GOOS=windows go build -tags "!ci,!android,!ios,!wasm,!test_web_driver" -o bin/godo.exe cmd/godo/main.go

  build:linux:
    desc: Build for Linux
    deps: [wire:linux]
    cmds:
      - GOOS=linux CGO_ENABLED=0 FYNE_RENDERER=software go build -tags "!windows,!android,!ios,!wasm,!js" -o bin/godo cmd/godo/main.go

  build:docker:
    desc: Build using Docker
    deps: [clean]
    env:
      DOCKER_BUILDKIT: 1
    cmds:
      - docker build --target builder -f build/Dockerfile.linux -t godo-builder .
      - docker create --name godo-build godo-builder
      - docker cp godo-build:/app/bin/godo ./bin/
      - docker rm godo-build

  test:
    desc: Run tests
    deps: [wire]
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    deps: [fmt]
    cmds:
      - golangci-lint run ./...

  # CI/CD tasks
  ci:
    desc: Run CI checks locally
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build
