version: '3'

tasks:
  default:
    cmds:
      - task --list

  wire:
    desc: Generate wire dependency injection code
    dir: internal/di
    cmds:
      - wire

  build:
    desc: Build the application
    deps: [wire]
    cmds:
      - go build -o bin/godo cmd/godo/main.go

  run:
    desc: Run the application
    deps: [wire]
    cmds:
      - go run cmd/godo/main.go

  test:
    desc: Run tests
    deps: [wire]
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/

  dev:
    desc: Run development tasks (fmt, lint, test, build)
    cmds:
      - task: fmt
      - task: wire
      - task: lint
      - task: test
      - task: build

  install:
    desc: Install project dependencies
    cmds:
      - go install github.com/google/wire/cmd/wire@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go mod tidy
      - go mod download

  logs:
    desc: Watch application logs
    platforms: [windows]
    cmds:
      - cmd /C "type logs\godo.log"