version: '3'

vars:
  GO_VERSION: 1.23
  CURRENT_OS:
    sh: go env GOOS

tasks:
  clean:wire:
    desc: Clean up wire-generated files
    cmds:
      - |
        cd internal/container && \
        {{if eq OS "windows"}}
        cmd /c "del /f *_wire_gen.go 2>nul || exit 0"
        {{else}}
        rm -f *_wire_gen.go || true
        {{end}}

  wire:all:
    desc: Generate wire code for all platforms
    deps: [clean:wire]
    cmds:
      - cd internal/container && wire gen -tags windows
      - cd internal/container && wire gen -tags darwin
      - cd internal/container && wire gen -tags linux

  run:
    deps: [wire:all]
    cmds:
      - go run cmd/godo/main.go
