// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"fmt"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"github.com/google/wire"
	"github.com/jonesrussell/godo/internal/application/core"
	"github.com/jonesrussell/godo/internal/config"
	"github.com/jonesrussell/godo/internal/domain/repository"
	"github.com/jonesrussell/godo/internal/domain/service"
	storage2 "github.com/jonesrussell/godo/internal/domain/storage"
	"github.com/jonesrussell/godo/internal/infrastructure/gui"
	"github.com/jonesrussell/godo/internal/infrastructure/gui/mainwindow"
	"github.com/jonesrussell/godo/internal/infrastructure/gui/quicknote"
	"github.com/jonesrussell/godo/internal/infrastructure/gui/theme"
	"github.com/jonesrussell/godo/internal/infrastructure/logger"
	"github.com/jonesrussell/godo/internal/infrastructure/storage"
	"github.com/jonesrussell/godo/internal/infrastructure/storage/factory"
	"github.com/spf13/viper"
	"os"
	"path/filepath"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp() (core.Application, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	app := ProvideFyneApp(config)
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	unifiedNoteStorage, cleanup2, err := ProvideUnifiedStorage(logger, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	noteRepository := ProvideNoteRepositoryFromUnified(unifiedNoteStorage)
	noteService := ProvideNoteService(noteRepository, logger)
	noteStoreAdapter := ProvideNoteStoreAdapter(unifiedNoteStorage)
	window := ProvideMainWindow(app, noteStoreAdapter, logger, config)
	coreApp := core.New(app, config, logger, noteService, window, noteStoreAdapter)
	return coreApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// Provider Sets - Organized by concern
var (
	// ConfigSet provides the single source of truth for configuration
	ConfigSet = wire.NewSet(
		ProvideConfig,
	)

	// LoggingSet provides logging infrastructure
	LoggingSet = wire.NewSet(
		ProvideLogger,
	)

	// StorageSet provides data persistence
	StorageSet = wire.NewSet(
		ProvideUnifiedStorage,
		ProvideNoteStoreAdapter, wire.Bind(new(storage.NoteStore), new(*storage.NoteStoreAdapter)),
	)

	// ServiceSet provides business logic
	ServiceSet = wire.NewSet(
		ProvideNoteRepositoryFromUnified,
		ProvideNoteService,
	)

	// UISet provides user interface components
	UISet = wire.NewSet(
		ProvideFyneApp,
		ProvideMainWindow, wire.Bind(new(gui.MainWindow), new(*mainwindow.Window)), wire.Bind(new(mainwindow.Interface), new(*mainwindow.Window)),
	)

	// CoreSet provides essential services
	CoreSet = wire.NewSet(
		ConfigSet,
		LoggingSet,
		StorageSet,
		ServiceSet,
	)

	// AppSet provides the main application
	AppSet = wire.NewSet(core.New, wire.Bind(new(core.Application), new(*core.App)))
)

// Configuration provider - uses actual config system
func ProvideConfig() (*config.Config, error) {

	cfg := config.NewDefaultConfig()

	v := viper.New()
	v.SetConfigName("config")
	v.SetConfigType("yaml")

	if execPath, err := os.Executable(); err == nil {
		execDir := filepath.Dir(execPath)
		v.AddConfigPath(execDir)
	}

	v.AddConfigPath(".")

	if err := v.ReadInConfig(); err == nil {

		if configErr := v.Unmarshal(cfg); configErr != nil {
			fmt.Printf("Failed to parse config file, using defaults: %v\n", configErr)
		} else {
			fmt.Printf("Config file loaded: %s\n", v.ConfigFileUsed())
		}
	} else {
		fmt.Printf("No config file found, using defaults: %v\n", err)
	}

	return cfg, nil
}

// Logger provider
func ProvideLogger(cfg *config.Config) (logger.Logger, func(), error) {
	if cfg == nil {
		return nil, nil, fmt.Errorf("config is required")
	}

	logConfig := &logger.LogConfig{
		Level:    cfg.Logger.Level,
		Console:  cfg.Logger.Console,
		File:     cfg.Logger.File,
		FilePath: cfg.Logger.FilePath,
	}

	log, err := logger.New(logConfig)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create logger: %w", err)
	}

	cleanup := func() {
		if zapLogger, ok := log.(*logger.ZapLogger); ok {

			if err := zapLogger.Sync(); err != nil {
				fmt.Printf("Failed to sync logger: %v\n", err)
			}
		}
	}

	return log, cleanup, nil
}

// Unified storage provider
func ProvideUnifiedStorage(log logger.Logger, cfg *config.Config) (storage2.UnifiedNoteStorage, func(), error) {
	if log == nil {
		return nil, nil, fmt.Errorf("logger is required")
	}
	if cfg == nil {
		return nil, nil, fmt.Errorf("config is required")
	}

	storageConfig := &storage2.StorageConfig{
		Type: storage2.StorageType(cfg.Storage.Type),
		SQLite: storage2.SQLiteConfig{
			FilePath: cfg.Storage.SQLite.FilePath,
		},
		API: storage2.APIConfig{
			BaseURL:            cfg.Storage.API.BaseURL,
			Timeout:            cfg.Storage.API.Timeout,
			RetryCount:         cfg.Storage.API.RetryCount,
			RetryDelay:         cfg.Storage.API.RetryDelay,
			InsecureSkipVerify: cfg.Storage.API.InsecureSkipVerify,
		},
	}

	if cfg.Storage.Type == "" {
		log.Debug("Storage type not configured, falling back to SQLite", "path", cfg.Database.Path)
		storageConfig.Type = storage2.StorageTypeSQLite
		storageConfig.SQLite.FilePath = cfg.Database.Path
	}

	log.Debug("Creating unified storage", "type", storageConfig.Type)
	store, err := factory.NewUnifiedStorage(storageConfig, log)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create unified storage: %w", err)
	}

	cleanup := func() {
		if err := store.Close(); err != nil {
			log.Error("failed to close storage during cleanup", "error", err)
		}
	}

	return store, cleanup, nil
}

// Note store adapter provider
func ProvideNoteStoreAdapter(unifiedStore storage2.UnifiedNoteStorage) *storage.NoteStoreAdapter {
	return storage.NewNoteStoreAdapter(unifiedStore)
}

// Note repository provider from unified storage
func ProvideNoteRepositoryFromUnified(store storage2.UnifiedNoteStorage) repository.NoteRepository {
	return repository.NewNoteRepository(store)
}

// Note service provider
func ProvideNoteService(repo repository.NoteRepository, log logger.Logger) service.NoteService {
	return service.NewNoteService(repo, log)
}

// Fyne app provider
func ProvideFyneApp(cfg *config.Config) fyne.App {
	app2 := app.New()
	app2.
		SetIcon(theme.AppIcon())
	return app2
}

// Main window provider
func ProvideMainWindow(app2 fyne.App,

	store storage.NoteStore,
	log logger.Logger,
	cfg *config.Config,
) *mainwindow.Window {
	return mainwindow.New(app2, store, log, cfg.UI.MainWindow)
}

// Quick note provider
func ProvideQuickNote(app2 fyne.App,

	store storage.NoteStore,
	log logger.Logger,
	cfg *config.Config,
) *quicknote.Window {
	return quicknote.New(app2, store, log, cfg.UI.QuickNote)
}
