# Default configuration for Godo
app:
  name: "Godo"
  version: "0.1.0"
  id: "io.github.jonesrussell.godo"

database:
  path: "godo.db"

logger:
  level: "info"
  console: true
  file: false
  file_path: ""
  output: [ "stdout" ]
  error_output: [ "stderr" ]

hotkeys:
  quick_note:
    modifiers: [ "Ctrl", "Shift" ]
    key: "N"

ui:
  main_window:
    width: 800
    height: 600
    start_hidden: true
  quick_note:
    width: 400
    height: 200

http:
  port: 8080
  read_timeout: 30
  write_timeout: 30
  read_header_timeout: 10
  idle_timeout: 120
