# Default configuration for Godo
app:
  name: "Godo"
  version: "1.0.0"
  id: "com.jonesrussell.godo"

logger:
  level: "debug"
  console: true
  development: true
  encoding: "console"
  encoderConfig:
    timeKey: "time"
    levelKey: "level"
    nameKey: "logger"
    callerKey: "caller"
    messageKey: "msg"
    stacktraceKey: "stacktrace"
    timeEncoder: "iso8601"
    levelEncoder: "lowercase"

database:
  path: "godo.db"

ui:
  main_window:
    width: 800
    height: 600
    start_hidden: true
  quick_note:
    width: 200
    height: 100

hotkeys:
  quick_note:
    modifiers: [ "Ctrl", "Shift" ]
    key: "G"
