# Default configuration for Godo
app:
  name: "Godo"
  version: "0.1.0"
  id: "io.github.jonesrussell.godo"

database:
  path: "godo.db"

logger:
  level: "info"
  console: true

hotkeys:
  quick_note: "Ctrl+Alt+G"

ui:
  main_window:
    width: 800
    height: 600
    start_hidden: true
  quick_note:
    width: 400
    height: 200