# Development environment configuration
app:
  name: "Godo (Dev)"

database:
  path: "./data/godo_dev.db"

logging:
  level: "debug"
  console: true
  file:
    enabled: true
    path: "./logs/godo_dev.log"

ui:
  main_window:
    start_hidden: false 