# Test environment configuration
app:
  name: "Godo (Test)"

database:
  path: ":memory:"  # Use in-memory SQLite for tests

logger:
  level: "debug"
  console: true

ui:
  main_window:
    start_hidden: true 