name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev mingw-w64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Discussion
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            
            try {
              const release = await github.rest.repos.getRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag
              });

              await github.rest.discussions.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                category_id: "DIC_kwDOLKQXXc4CcDVS",
                title: `Release ${tag}`,
                body: release.data.body
              });
            } catch (error) {
              console.log('Error creating discussion:', error);
            } 