name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev mingw-w64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 'v1.26.2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Discussion
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            
            try {
              // First get the release by tag
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const release = releases.data.find(r => r.tag_name === tag);
              if (!release) {
                console.log('Release not found for tag:', tag);
                return;
              }

              // Get discussion categories to find the Releases category
              const categories = await github.rest.discussions.listDiscussionCategories({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const releasesCategory = categories.data.find(c => c.name === 'Releases');
              if (!releasesCategory) {
                console.log('Releases discussion category not found');
                return;
              }

              // Create the discussion
              await github.rest.discussions.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                category_id: releasesCategory.id,
                title: `Release ${tag}`,
                body: release.body
              });
            } catch (error) {
              console.log('Error creating discussion:', error);
              // Don't fail the workflow if discussion creation fails
            } 