name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            libx11-dev \
            libxcb1-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libx11-xcb-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libxxf86vm-dev

      - name: Install Wire
        run: go install github.com/google/wire/cmd/wire@latest

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Wire code
        run: |
          cd internal/container
          wire gen -tags linux
          wire gen -tags windows
          wire gen -tags darwin

      - name: Build all platforms
        run: task build:all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/godo.exe
            bin/godo-linux
          generate_release_notes: true
          draft: false
          prerelease: false 